### ISSUE TITLE
what is eval in jsons?

### ISSUE THREAD

**Issue by IQ17** [clovaai/lookwhostalking#3]
Hi, great work!

In jsons, there are label and eval, and what is eval for ?

**Comment by 117kyjin** [comment]
"Label" is the annotation of each frame, and has 1 (active) or 0 (non-active). 
On the other hand, "eval" indicates whether each frame is evaluated or not. The start and end frames of each track are excluded from evaluation(, since it is nearly impossible to get accurate timestamps for boundary frames).

**Comment by IQ17** [comment]
thanks!
